//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_4nEK5zq3f"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "2db1iqvn4ovlaohut73gp3kb8s"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1moqbd8t30tmeq2a7kvk8393qe432ru6hcihfr8373nj1thufn0h"
