//
//  Consumable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Consumable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _consumableType: String?
    var _imagePath: String?
    var _name: String?
    var _subConsumableType: String?
    
    class func dynamoDBTableName() -> String {

        return "addysfitnessapp-mobilehub-805122985-Consumable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_consumableType"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_consumableType" : "consumableType",
               "_imagePath" : "imagePath",
               "_name" : "name",
               "_subConsumableType" : "subConsumableType",
        ]
    }
}
